### PR TITLE
Copy CHANGELOG.md stub over from twbs/bootstrap

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by glebm** [comment]
Mmm. What if GitHub goes down / disappears in 10 years, and somebody is digging through legacy code that's using it? IMO Changelogs are part of the documentation and should be stored with the gem.

**Comment by cvrebert** [comment]
> What if GitHub goes down / disappears in 10 years, and somebody is digging through legacy code that's using it?

Probably someone would have migrated that data to some other project hosting site, since there's an open API to fetch it from (https://developer.github.com/v3/repos/releases/ ) and Bootstrap is/was kind of a big deal :-)

But if y'all on Sass Team (I guess it should really be "Ruby Team" now?) wanna differ from core and keep an additional, manually-updated copy of your changelog, that's totally within your prerogative IMO. It's your small maintenance burden, not Core Team's :-)
I was merely trying to help get all the repo skeleton files in place.

**Comment by glebm** [comment]
There are other reasons to keep the changelog with the code:
* Requiring the people to use a proprietary service to read the changelog is a big deal. IIRC some japanese developers refused to contribute to rubyspec because the only means of accessing it were via a proprietary service.
* A developer may want to read changelog when they are not connected to the internet.

I think the above justifies the tiny maintenance burden, and we should do it upstream as well.

**Comment by glebm** [comment]
Anyway, merging, and will modify the copy to indicate that we do both. Thanks!

**Pull request merged**
