### PR TITLE
Fix: Replace color-adjust to print-color-adjust.

### PR DESCRIPTION
**Pull request by lorenzk**
Hi everybody! First: Thanks for a rock solid gem!

The color-adjust shorthand is currently deprecated and makes autoprefixer complain.

I have a code base on 4.6 that I cannot upgrade to 5.0 any time soon, and this would fix the deprecation warnings from autoprefixer.

Cheers!

### CODE REVIEW

**Comment by lorenzk** [comment]
For reference, here is the [W3C deprecation notice](https://drafts.csswg.org/css-color-adjust-1/#propdef-color-adjust): 

> The [color-adjust](https://drafts.csswg.org/css-color-adjust-1/#propdef-color-adjust) shorthand is currently deprecated. Authors should use the more specific [print-color-adjust](https://drafts.csswg.org/css-color-adjust-1/#propdef-print-color-adjust) property, to avoid accidentally resetting performance-based color adjustments in other contexts than the one intended.

**Comment by glebm** [comment]
Fixes to the CSS should be made upstream in [twbs/bootstrap](http://github.com/twbs/bootstrap)

**Comment by lorenzk** [comment]
Oh, sorry, I didn't know. It appears upstream has already integrated this into their [`v4-dev` branch](https://github.com/twbs/bootstrap/blob/82a1f334cf02c6b1fbb27d5da6afb89a80223c31/scss/_custom-forms.scss#L16), so I'll just wait for that change to trickle down.

Thanks!

**Comment by glebm** [comment]
Ah, good to know. I've pushed the latest updates from upstream to https://github.com/twbs/bootstrap-rubygem/tree/4.6-stable

**Pull request closed without merging**
