### PR TITLE
Update Gem for Bootstrap 4 Alpha 3

### PR DESCRIPTION
**Pull request by pinglamb**
I used the awesome rake task `rake update[v4.0.0-alpha.3]` to update for v4 alpha 3.

I think it is better if this gem can stick to the version number of Bootstrap core. Right now the latest released gem is of version `4.0.0.alpha3` which is a little bit confusing.

#46

### CODE REVIEW

**Comment by glebm** [comment]
Thanks!

**Comment by kkirsche** [comment]
Thanks! Looking forward to seeing this pushed out to rubygems.org 😃

**Comment by glebm** [comment]
I'm wondering what to do with the version number: whether to release alpha4 or something like alpha3.1 to better match the upstream alpha version in the future. Leaning towards alpha3.1 atm.

**Comment by pinglamb** [comment]
+1 for alpha3.1

**Comment by glebm** [comment]
Done: https://github.com/twbs/bootstrap-rubygem/releases/tag/v4.0.0.alpha3.1

**Pull request merged**
