### PR TITLE
Update to Alpha 6

### PR DESCRIPTION
**Pull request by bgentry**
Tried to follow the previous update process by running the rake task and then separately bumping the versions. I had to remove some outdated references to bootstrap-flex in the rake update task since that file is gone now (flexbox for all :tada:)

### CODE REVIEW

**Comment by bgentry** [comment]
I've updated my project to use this and it seems to be working fine (aside from the expected changes like getting rid of `-xs`). That being said, I'm not using a ton of components 🤷‍♂️

**Comment by arteezy** [comment]
Please merge ASAP, can't wait to play with new alpha

**Comment by bgentry** [comment]
@arteezy pretty easy to specify `github: 'bgentry/bootstrap-rubygem', branch: 'alpha-6'` in the mean time 🙂

**Comment by glebm** [comment]
@bgentry Thank you!

**Pull request merged**
