### PR TITLE
Upgrade to 5.3.0

### PR DESCRIPTION
**Pull request by tim-carey-code**
- Downloaded 5.3.0 source files from bootstrap
- Replaced js and scss files with new ones

### CODE REVIEW

**Comment by dpaola2** [comment]
@glebm Are there contributor rules? This PR fixes some missing functionality for us, I wonder if there is anything else to provide to get it merged. Thank you for your efforts 🙇‍♂️

**Comment by ajoabraham** [comment]
How can we get this merged?  I see no reviewers assigned.

**Comment by tim-carey-code** [comment]
> How can we get this merged? I see no reviewers assigned.

Not sure. There is no option to assign a reviewer for some reason

**Comment by torrocus** [comment]
@glebm Can we somehow help with the code review to improve the process of merging these changes?

**Comment by glebm** [comment]
5.3.0.alpha3 has been released to rubygems

**Pull request closed without merging**
